# this is a local file that MUST be ignored
# by git, and contains the actual secrets, tokens, custom config etc.
spring.config.import=file:env.properties
spring.application.name=D5-gestione-eventi

# SERVER CONFIG
server.port=${SERVER_PORT}
server.local-domain=${SERVER_LOCAL_DOMAIN}

# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# Json Web Token
jwt.secret=${JWT_SECRET}